  export const hospitalData = [
    {
      id: 1,
      name: '病院01',
      kind: '内科',
      address: '東京都新宿区',
      image: '@/image/01.jpg',
      description: '病院01の説明',
      phone: '03-1234-5678',
    },
    {
      id: 2,
      name: '病院02',
      kind: '外科',
      address: '東京都渋谷区',
      image: '/image/02.jpg',
      description: '病院02の説明',
      phone: '03-1234-5678',
    },
    {
      id: 3,
      name: '病院03',
      kind: '小児科',
      address: '東京都豊島区',
      image: '/image/01.jpg',
      description: '病院03の説明',
      phone: '03-1234-5678',
    },
    {
      id: 4,
      name: '病院04',
      kind: '小児科',
      address: '東京都千代田区',
      image: '/image/02.jpg',
      description: '病院04の説明',
      phone: '03-1234-5678',
    },
    {
      id: 5,
      name: '病院05',
      kind: '小児科',
      address: '東京都千代田区',
      image: '/image/01.jpg',
      description: '病院04の説明',
      phone: '03-1234-5678',
    },
    {
      id: 5,
      name: '病院06',
      kind: '小児科',
      address: '東京都千代田区',
      image: '/image/02.jpg',
      description: '病院04の説明',
      phone: '03-1234-5678',
    },
    {
      id: 7,
      name: '病院07',
      kind: '外科',
      address: '東京都渋谷区',
      image: '/image/01.jpg',
      description: '病院02の説明',
      phone: '03-1234-5678',
    },
    {
      id: 8,
      name: '病院08',
      kind: '外科',
      address: '東京都渋谷区',
      image: '/image/02.jpg',
      description: '病院02の説明',
      phone: '03-1234-5678',
    },
    {
      id: 9,
      name: '病院09',
      kind: '外科',
      address: '東京都渋谷区',
      image: '/image/01.jpg',
      description: '病院02の説明',
      phone: '03-1234-5678',
    },
    {
      id: 10,
      name: '病院10',
      kind: '内科',
      address: '東京都新宿区',
      image: '/image/02.jpg',
      description: '病院01の説明',
      phone: '03-1234-5678',
    },
    {
      id: 11,
      name: '病院11',
      kind: '内科',
      address: '東京都新宿区',
      image: '/image/01.jpg',
      description: '病院01の説明',
      phone: '03-1234-5678',
    },
    {
      id: 12,
      name: '病院12',
      kind: '内科',
      address: '東京都新宿区',
      image: '/image/02.jpg',
      description: '病院01の説明',
      phone: '03-1234-5678',
    },
 ];